- hosts: master-node
  become: true
  tasks:

    - name: ensure that git and snapd is installed on the server
      ansible.builtin.apt:
        name:
          - git
          - snapd
        state: present

    - name: start and enable snapd
      ansible.builtin.systemd:
        name: snapd.service
        enabled: true
        state: started

    - name: Copy install script for cri-dockerd
      ansible.builtin.copy:
        src: ./install.sh
        dest: /root/install.sh
        mode: '0777'

    - name: configure cri-dockerd
      become: true
      ansible.builtin.shell: chmod +x ./install.sh && /bin/sh install.sh


    - name: initialize the cluster
      become: true
      ansible.builtin.shell: kubeadm init --cri-socket /run/cri-dockerd.sock
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: true
      ansible.builtin.file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copies admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: ~/.kube/config
        remote_src: true
        owner: root

    - name: install Pod network
      become: true
      ansible.builtin.shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml 
      args:
        chdir: $HOME

    - name: Get the token for joining the worker nodes
      become: true
      ansible.builtin.shell: kubeadm token create  --print-join-command
      register: kubernetes_join_command

    - ansible.builtin.debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file.
      become: true
      local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="./kubernetes_join_command" mode=0777