- hosts: worker-nodes
  become: true
  gather_facts: true

  tasks:

    - name: ensure that git and snapd is installed on the server
      ansible.builtin.apt:
        name:
          - git
          - snapd
        state: present

    - name: start and enable snapd
      ansible.builtin.systemd:
        name: snapd.service
        enabled: true
        state: started

    - name: Copy install script for cri-dockerd
      ansible.builtin.copy:
        src: ./install.sh
        dest: /root/install.sh
        mode: '0777'

    - name: configure cri-dockerd
      become: true
      ansible.builtin.shell: chmod +x ./install.sh && /bin/sh install.sh




    - name: Copy join command from Ansiblehost to the worker nodes.
      become: true
      ansible.builtin.copy:
        src: ./kubernetes_join_command
        dest: /tmp/kubernetes_join_command
        mode: 0777
      ignore_errors: false
  
    - name: Join the Worker nodes to the cluster.
      become: true
      command: sh /tmp/kubernetes_join_command
      register: joined_or_not
